# Setup
title:               Shannon Lally Test Blog
tagline:             ‘I have no clue what is going on’
description:         'Why the website not have the right format :('
url:                 http://Shannon-Lally.github.io/IDH-blog/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Shannon Lally
  url:               http://Shannon-Lally.github.io
  email:             lally.sh@northeastern.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
